### ISSUE TITLE
this package needs tests

### ISSUE THREAD

**Issue by rabernat** [ECCO-GROUP/ECCOv4-py#1]
This package contains lots of useful routines for dealing with ecco output. Fantastic work @ifenty for such a valuable contribution! 🥇 

As we discussed at OSM, a test suite is very important for a community open source package. Matt Rocklin sums them up in [this blog post](http://matthewrocklin.com/blog/work/2016/02/08/tests) better than I ever could.

Among the many advantages, the exercise of writing tests would force the ecco community to think precisely about what features the ECCOv4-py package needs to have in order to serve its users.

For an example of what such a test suite might look like, you can have a look at xmitgcm:
https://github.com/xgcm/xmitgcm/blob/master/xmitgcm/test/test_mds_store.py

**Comment by ifenty** [comment]
@rabernat  I added a routine that can test the loading and conversion of llc compact format files to and from the 5 facets to the 13 tiles

'test_llc_array_loading_and_conversion'.

I am sure there is a better way of doing this kind of test but this is a first step!

**Comment by timothyas** [comment]
I think that we should some automated testing to this package, then as we add tests (which I've started to do in the directory `ecco_v4_py/test`) we will see these go into action for each new PR. This would hopefully give us more confidence in new PRs not breaking the code.

Based on my limited knowledge, I think it would good to start with [codecov](https://docs.codecov.io/docs) and [travis-ci](https://docs.travis-ci.com/). I went through the process of integrating these on one of my private work repositories, since I have an educational account through github. I would happily get them set up for this repo, but it seems I need the right permissions to do this.

However, the first hurdle is $$, because as far as I understand this would require some subscription money. It looks like:
- travis-ci (which does the automated testing on PRs) is ~$129/month for 2 concurrent jobs, which I guess means we can test two different python environments? See [travis-ci pricing here](https://travis-ci.com/account/subscription?billingStep=1) here
- codecov (which tells you how much of the code is being tested) is less clear. They have a "free" subscription for up to 5 users, so I'm not sure this would work for ECCO-GROUP. Otherwise it's $10/mo. See [codecov pricing here](https://codecov.io/pricing)

Would this sort of thing be coverable in ECCO's budget? I think it is super valuable, and would really help our development process. It seems common place in a lot of open source projects, so it would be nice to get on board. What do you think @ifenty @owang01?

**Comment by rabernat** [comment]
Travis is completely free for open source projects. None of this will cost a dime.

**Comment by timothyas** [comment]
My bad! Thanks @rabernat!
