### ISSUE TITLE
`get_section_masks` doesn't produce a straight meridional section

### ISSUE THREAD

**Issue by pittwolfe** [ECCO-GROUP/ECCOv4-py#118]
I'm trying to use `get_section_masks` to make a meridional section up the Florida coast. This is deep within the lat/lon part of the grid, so I would have expected specifying the end points as the cell centers at the same longitude would produce a straight meridional section, but instead the path jukes to the side at one point. 

The included image shows the problem. The two end points are XC and YC at (i, j) = (73, 47) and (i, j) = (66, 73) on tile 10—these work out to 25.676ºN, 85.5ºW and 31.833ºN, 85.5ºW. The shading is maskC from `get_section_masks` with blue and red for 0 and 1, respectively, the (i,j) grid is contoured in black at an interval of 10, and the line connecting the two points is also in black. 
![meridional_section](https://user-images.githubusercontent.com/4522204/113633098-61528680-963a-11eb-9fba-c6d9cbe58600.png)

Anyone have any idea what's happening here? If `get_section_masks` has a hard time making a meridional section along a grid line in the lat/lon part of the grid, it makes me worry about its reliability in more complex situations. 

It's easy enough to make a meridional section by hand in the lat/lon part of the grid, but other sections in other parts of the grid are tricky, so I'd rather use `get_section_masks`.

**Comment by timothyas** [comment]
Hey @pittwolfe, thanks for reporting this. I agree, that is strange and although there are straightforward ways to create a mask like that, `get_section_masks` shouldn't have an issue. 

Could you post the code used to create this?

**Comment by pittwolfe** [comment]
Github wouldn't let me paste in a Jupyter notebook, so here's the code:

```
import os
import numpy as np
import matplotlib.pyplot as plt
import xarray as xr
import ecco_v4_py as ecco

# Load your grid
grid_dir = os.path.join(os.environ['HOME'], 'project/Research/CoA/fct/ecco/grid')
grid =  xr.open_dataset(os.path.join(grid_dir, 'grid.nc'))

# Define the endpoints of the section.
ix1 = (73, 47)
ix2 = (66, 47)
XC = grid.XC.sel(tile = 10)
YC = grid.YC.sel(tile = 10)

pt1 = (float(XC.isel(i=ix1[0], j=ix1[1])), 
       float(YC.isel(i=ix1[0], j=ix1[1])),
      )
print(pt1)
(-80.50000000000001, 25.676053888853584)

pt2 = (float(XC.isel(i=ix2[0], j=ix2[1])), 
       float(YC.isel(i=ix2[0], j=ix2[1])),
      )
print(pt2)
(-80.50000000000001, 31.83304396597359)

maskC, maskW, maskS = ecco.get_section_line_masks(pt1, pt2, grid)

# plot the mask
I, J = np.meshgrid(grid.i, grid.j)

plt.pcolormesh(XC, YC, maskC.isel(tile=10), shading='nearest')
plt.contour(XC, YC, I, levels=np.arange(0, 100, 10), colors='k', linestyles='-', linewidths=1)
plt.contour(XC, YC, J, levels=np.arange(0, 100, 10), colors='k', linestyles='-', linewidths=1)
plt.plot((pt1[0], pt2[0]), (pt1[1], pt2[1]), '-k', alpha=.75)
plt.title('tile 10')
plt.xlabel('XC')
plt.ylabel('YC')
plt.show()
```

**Comment by timothyas** [comment]
Hey @pittwolfe, sorry for a little delay in getting back to you. I was able to reproduce your error, thanks for the clear description & code. I think I have a solution, but the root cause of the problem is unclear. 

Check out [this gist](https://gist.github.com/timothyas/45eb1a4b2b0dc61903155745fb4c128f), which reproduces the problem, then shows that if we cast the variables as single precision, `numpy.float32`, the problem goes away. There is a suspicious digit in the 16th place in the first element of pt1 and pt2. I think this is a safe workaround, because (as shown there) if we look at the XC values at a single latitude we see some have this extra digit, some don't. As you mentioned, this is well within the lat/lon part of the grid, and I think it is clear that the intention was not to have this extra digit...

The question remains how it got there and how to fix it going forward. Interestingly in release 3 and 4 the data file specifies to write binaries at single precision:

https://github.com/ECCO-GROUP/ECCO-v4-Configurations/blob/31ae07ced0f39c1d84d3675b909370b08c188f8c/ECCOv4%20Release%203/namelist/data#L63-L64

and yet the meta/data pairs I have (and likely the files that make up your netcdf grid) are written to double precision.

I guess another question is how `get_section_masks` is sensitive to this small overlap. Unfortunately I don't have a quick answer to that question...

**Comment by timothyas** [comment]
@ifenty is the grid written with a different data file than the one in ECCO-v4-Configurations? Also, do you know the precision of the til*.mitgrid files, since these are the files which originally specify the grid?

**Comment by ifenty** [comment]
@timothyas 

the default format of the til.*mitgrid files are written as big endian, double precision floats and Fortran order.

in Python datatype language: '>f8'

**Comment by ifenty** [comment]
> The question remains how it got there and how to fix it going forward. Interestingly in release 3 and 4 the data file specifies to write binaries at single precision:

This is a good question.... we inherited the tile.*.mitgrid files.  Possibly the precision of those fields was originally 32 bit but they were written as 64 bit and somehow the trailing 1 value was then introduced in the mantissa.  

@pittwolfe Casting any 64 bit grid parameter arrays to 32 bit is a workaround.  Another options is to use our 'latest' grid files which stores all of the float arrays in 32 bit precision.  I confirmed that in the new grid files the XC value of your *pt1* is -80.5 without the trailing 1.
