### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by rabernat** [ECCO-GROUP/ECCOv4-py#3]
Thanks again for getting the ball rolling on this important package! I just had a look through the source code and noticed that it is written only for python 2. This is a big problem, as python 2 will not be maintained past 2020. Nearly all scientific python packages (including numpy and xarray) are dropping python 2 support then or before.
http://python3statement.org/

Since this is a brand new package without any legacy code to support, there is really no reason to write it in python 2. We definitely do not want to encourage new python users (potentially a significant fraction of ecco users) to start from 2 instead of 3!

**Comment by ifenty** [comment]
Ryan,

 

Is it possible to rewrite the code so that it is compatible with both Python 2 and 3 or would we need two versions? 

                                       

Ian

 

 

On 2/20/18, 1:14 PM, "Ryan Abernathey" <notifications@github.com> wrote:

 

Thanks again for getting the ball rolling on this important package! I just had a look through the source code and noticed that it is written only for python 2. This is a big problem, as python 2 will not be maintained past 2020. Nearly all scientific python packages (including numpy and xarray) are dropping python 2 support then or before.
http://python3statement.org/

Since this is a brand new package without any legacy code to support, there is really no reason to write it in python 2. We definitely do not want to encourage new python users (potentially a significant fraction of ecco users) to start from 2 instead of 3!

**Comment by rabernat** [comment]
It is definitely possible to support both 2 and 3 with a single code base! This is what most scientific python projects do. The process is described very well here:
http://python-future.org/index.html

If you are not using complicated iterating, class structures, or unicode strings, it is likely that 99% of your incompatibility comes from using `print` without parentheses. This is trivial to fix.

The first step would be do develop comprehensive test coverage (see #1) which validates the functionality of the package under python 2. Then you would create a test environment under python 3 and use it to make sure you tests all pass with both.

**Comment by ifenty** [comment]
Ryan,

 

Great!    I’ll take a look at modifying the code to support Python 2 and 3 and creating a test environment.

 

Ian

 

 

On 2/21/18, 12:02 PM, "Ryan Abernathey" <notifications@github.com> wrote:

 

It is definitely possible to support both 2 and 3 with a single code base! This is what most scientific python projects do. The process is described very well here:
http://python-future.org/index.html

If you are not using complicated iterating, class structures, or unicode strings, it is likely that 99% of your incompatibility comes from using print without parentheses. This is trivial to fix.

The first step would be do develop comprehensive test coverage (see #1) which validates the functionality of the package under python 2. Then you would create a test environment under python 3 and use it to make sure you tests all pass with both.

**Comment by ifenty** [comment]
@rabernat As far as I can tell, we are now Python 2 and 3 compatible!
